# Generated by Django 6.0.3 on 2026-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="emails",
            field=models.EmailField(max_length=254),
        ),
    ]
