# Generated by Django 6.0.3 on 2026-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0002_alter_contact_emails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="emails",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="contact",
            name="msg",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
